name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run linting
      run: npm run lint || echo "Linting not configured yet"
      
    - name: Build project
      run: npm run build || echo "Build not configured yet"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security audit
      run: npm audit --audit-level moderate || echo "Security audit completed"
      
    - name: Check for vulnerabilities
      run: |
        if command -v npx &> /dev/null; then
          npx audit-ci --config audit-ci.json || echo "Audit CI not configured"
        else
          echo "npx not available"
        fi

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check README exists
      run: test -f README.md && echo "README.md found" || exit 1
      
    - name: Check LICENSE exists
      run: test -f LICENSE && echo "LICENSE found" || exit 1
      
    - name: Check CONTRIBUTING exists
      run: test -f CONTRIBUTING.md && echo "CONTRIBUTING.md found" || exit 1
      
    - name: Check CODE_OF_CONDUCT exists
      run: test -f CODE_OF_CONDUCT.md && echo "CODE_OF_CONDUCT.md found" || exit 1
      
    - name: Check SECURITY exists
      run: test -f SECURITY.md && echo "SECURITY.md found" || exit 1
      
    - name: Check CHANGELOG exists
      run: test -f CHANGELOG.md && echo "CHANGELOG.md found" || exit 1
